name: CI
on: 
    push:
        branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Update Chrome
          run: npm run update:chrome
        - name: Test
          # run: npm run test:firefox:headless
          run: npm run test:chrome:headless:login

        - name: Install allure
          run: npm install -g allure-commandline --save-dev
        
        - name: Reports Generate
          run: npx allure generate ./allure-results --clean    
          
        - uses: actions/upload-artifact@master
          with:
            name: allure-results
            path: allure-results
            retention-days: 20
      
        - name: Get Allure history
          uses: actions/checkout@v2
          if: always()
          continue-on-error: true
          with:
              ref: gh-pages
              path: gh-pages

        - name: Allure Report action from marketplace
          uses: simple-elf/allure-report-action@master
          if: always()
          with:
              allure_results: allure-results
              gh_pages: gh-pages
              allure_report: allure-report
              allure_history: allure-history
              keep_reports: 20

        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
              PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              PUBLISH_BRANCH: gh-pages
              PUBLISH_DIR: allure-history
        
          
